### ISSUE TITLE
transcriptic resources command not working?

### ISSUE THREAD

**Issue by hgbrian** [transcriptic/transcriptic#53]
Just installed in Python 3.5 with `pip install transcriptic` (transcriptic==3.2.3)

```
briann$ transcriptic resources water

Results for 'water':
             Resource Name              |                 Vendor                 |              Resource ID
------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/briann/anaconda/envs/clab/bin/transcriptic", line 11, in <module>
    sys.exit(cli())
  File "/Users/briann/anaconda/envs/clab/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/briann/anaconda/envs/clab/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Users/briann/anaconda/envs/clab/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/briann/anaconda/envs/clab/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/briann/anaconda/envs/clab/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Users/briann/anaconda/envs/clab/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/briann/anaconda/envs/clab/lib/python3.5/site-packages/transcriptic/cli.py", line 479, in resources
    if i["provisionable"] and not i["reservable"]:
KeyError: 'provisionable'
```

**Comment by yangchoo** [comment]
Thanks for listing the issue, Brian. Will look into this.

In the meantime, you could look at resources by going to https://secure.transcriptic.com/_commercial/kits

**Comment by yangchoo** [comment]
Seems like the base query itself (`api.resources(query)`) still works, but the return structure has changed.

We'll have to re-parse and restructure the return. For now, if you would prefer to access the raw resource list via the API, feel free to use the direct api call.

**Comment by yangchoo** [comment]
Furthermore, if you are interested in a mapping of resources to resource_ids but are not really invested in obtaining them through the API, you could also use the recently published Autoprotocol Utilities repository. 
In particular, https://github.com/autoprotocol/autoprotocol-utilities/blob/master/autoprotocol_utilities/resource_helpers.py#L345 should be of interest to you

**Comment by hgbrian** [comment]
Thanks for the assistance yangchoo. I'll try the API. I tried to `pip install autoprotocol_utilities` but I don't think it's in python 3 yet?

**Comment by yangchoo** [comment]
Sorry bout the delayed response, Brian. I checked in with the maintainers of `autoprotocol_utilities` and it seems like Python3 compatibility is planned but currently scheduled for early next week.
In the meantime, I've just submitted a pull-request for fixing this bug.

Thanks again for spotting the bug and filling an issue :)
