### ISSUE TITLE
CLI: Listing protocols error

### ISSUE THREAD

**Issue by bmiles** [transcriptic/transcriptic#95]
```
$ t protocols

Traceback (most recent call last):
  File "/usr/local/bin/transcriptic", line 11, in <module>
    load_entry_point('transcriptic==4.0.0', 'console_scripts', 'transcriptic')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "build/bdist.macosx-10.12-x86_64/egg/transcriptic/cli.py", line 322, in protocols
NameError: global name 'remote' is not defined```

**Comment by transcripticpll** [comment]
Resolved by 62e1ab44
